-- ============================================
-- Generated by: export_to_sql.py
-- Generated at: 2026-08-19 16:02:57
-- Total records: 18
-- ============================================

BEGIN;

INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('示例餐厅', '本地苏帮菜', '¥50-100', '4.5', 'https://example.com', '周一-周日 11:00-21:00', '0512-12345678', '否', '10-20分钟', '平价小吃', '示例条目：这是一个用来展示 CSV 格式的示例行。');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('豌豆花开文星店', '川渝口味', '¥13-30', '5.0', 'https://surl.amap.com/cyKzztUx8yD', '周一-周日 8:00-22:00', '0512-62817117 18068448817', '否', '5-20分钟', '平价小吃', '回国必吃 推荐凉面');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('地锅居（翰林邻里中心店）', '江浙菜', '¥54', '4.6', 'https://surl.amap.com/22vNFxRE1vv', '周五 11:00-14:00;16:30-21:30;周六-周日 11:00-14:30;16:00-21:30;周三-周四 11:00-14:00;16:00-21:30', '18952405766', '否', '5-20分钟', '平价小吃', '必点地锅鸡');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('小海鲜大排档', '海鲜', '¥100-150', '4.8', 'https://surl.amap.com/ds0meG211gIQ', '4:30-2:00', '15784506296', '否', '15-30分钟', '海鲜餐厅', '椒盐皮皮虾');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('阿泰藏书羊肉•小龙虾•烧烤', '烧烤', '¥50-100', '4.6', 'https://surl.amap.com/dwB9pJA137hU', '10:00-2:00', '17201997254', '否', '5-10分钟', '烧烤', '羊肉串 小龙虾🦞建议团购');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('重庆鸡公煲川味烤鱼(文荟广场店)', '火锅鸡', '¥42/人', '4.1', 'https://surl.amap.com/dA53Avc17gLt', '9:30-23:30', '15784601495', '否', '5-20分钟', '火锅鸡', '鸡公煲');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('文景夜市', '夜市', '¥10-30', '4.6', 'https://surl.amap.com/dM93aF8sbnb', '16:00-22:00', 'NULL', '否', '15-15分钟', '夜市小吃', '夜市美食');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('文缘夜市', '夜市', '¥19/人', '4.7', 'https://surl.amap.com/bRYe8FYGfEX', '20:00-4:00', 'NULL', '否', '15-15分钟', '夜市小吃', '夜市美食');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('食在湘概念湘菜', '湘菜', '¥55/人', '4.6', 'https://surl.amap.com/bkqkGmSDahG', '10:00-22:00', '17895067596', '否', '10-20分钟', '平价小吃', '剁椒鱼头');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('孚味浅草日本料理(翰林店)', '日本料理', '¥77/人', '4.6', 'https://surl.amap.com/diB7zem1s1zk', '9:00-14:00;16:00-21:00', '17201945627', '否', '10-20分钟', '日本料理', '三文鱼手握🍣和香芒鹅肝');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('狗喜头鱼头', '中餐', '¥83/人', '4.5', 'https://surl.amap.com/dpsHtlItfzC', '11:00-14:00;17:00-22:30', '15784506296', '否', '10-20分钟', '中餐', '红烧鱼头');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('十三朝手擀爆肚面', '西安面', '¥20/人', '4.7', 'https://surl.amap.com/5PQXkiS1A4OA', '10:30-21:00', '13584888317', '否', '5-20分钟', '平价小吃', '爆肚面');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('大铭油边王', '烧烤', '¥74/人', '4.7', 'https://surl.amap.com/dvvDAse1d5g7', '17:30-1:00', 'NULL', '否', '5-10分钟', '烧烤', '油边 凉面');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('金山小馆(中海双湾花园店)', '中餐', '¥78/人', '4.7', 'https://surl.amap.com/g1JkCFUi6aG', '24h营业', '17201996948', '否', '10-20分钟', '中餐', '特色烤鱼 招牌牛蛙 麻辣猪蹄锅');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('山中无老虎·鱼蛙火锅(尹山湖店)', '火锅', '¥71/人', '4.6', 'https://surl.amap.com/f1RdivMzcdn', '10:30-13:30;16:30-24:00', '1780441270', '否(可订座)', '5-20分钟', '火锅', '鱼蛙火锅');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('小天同学炭火厨房', '日式烧鸟', '¥80/人', '4.7', 'https://surl.amap.com/hC5rtcq1j6GE', '17:00-01:00', '15784509383', '否(可订座)', '5-20分钟', '日式烧鸟', '和牛泡菜锅');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('李呱呱重庆火锅(尹山湖店)', '重庆火锅', '¥99/人', '4.5', 'https://surl.amap.com/fby0nNE1obGR', '11:00-14:00;16:00-2:00', '13063738919', '否(可订座)', '5-20分钟', '火锅', '重庆火锅');
INSERT INTO suzhou_food (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `contact`, `reservation_needed`, `queue_time`, `tags`, `notes`) VALUES ('噶闹棒铁锅豆花牛肉', '豆花/豆腐脑', '¥82/人', '4.5', 'https://surl.amap.com/bR4aG5o1m7Bd', '10:00-14:00;16:30-24:00', '15151659564', '否', '5-20分钟', '豆花/豆腐脑', '铁锅豆花牛肉');

COMMIT;
