#!/usr/bin/env python3
"""
CSV to SQL Converter
Reads CSV and generates INSERT statements
"""

import csv
import os
import sys
from datetime import datetime

CSV_PATH = os.getenv('CSV_PATH', 'food-original.csv')
SQL_PATH = os.getenv('SQL_PATH', 'data/food.sql')

def escape_sql_value(val):
    """Escape SQL string values"""
    if val is None or str(val).strip() == '':
        return 'NULL'
    val = str(val)
    escaped = val.replace('\\', '\\\\').replace("'", "''")
    return f"'{escaped}'"

def main():
    print(f"Reading CSV: {CSV_PATH}")
    print(f"Generating SQL: {SQL_PATH}")
    
    # 确保输出目录存在
    os.makedirs(os.path.dirname(SQL_PATH), exist_ok=True)
    
    try:
        with open(CSV_PATH, 'r', encoding='utf-8-sig') as csvfile:
            reader = csv.DictReader(csvfile)
            fields = reader.fieldnames
            
            if not fields:
                print("❌ CSV has no headers", file=sys.stderr)
                sys.exit(1)
            
            rows = list(reader)
            
    except FileNotFoundError:
        print(f"❌ CSV file not found: {CSV_PATH}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error reading CSV: {e}", file=sys.stderr)
        sys.exit(1)
    
    if not rows:
        print("⚠️ Warning: CSV is empty")
    
    with open(SQL_PATH, 'w', encoding='utf-8') as sqlfile:
        sqlfile.write("-- ============================================\n")
        sqlfile.write("-- Generated by: export_to_sql.py\n")
        sqlfile.write(f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        sqlfile.write(f"-- Total records: {len(rows)}\n")
        sqlfile.write("-- ============================================\n\n")
        
        sqlfile.write("BEGIN;\n\n")
        
        for idx, row in enumerate(rows, 1):
            values = []
            for f in fields:
                val = row.get(f, '')
                values.append(escape_sql_value(val))
            
            fields_quoted = [f'`{f}`' for f in fields]
            sqlfile.write(f"INSERT INTO suzhou_food ({', '.join(fields_quoted)}) VALUES ({', '.join(values)});\n")
            
            if idx % 100 == 0:
                sqlfile.write("\n")
        
        sqlfile.write("\nCOMMIT;\n")
    
    print(f"✅ SQL generated successfully: {SQL_PATH}")
    print(f"📊 Records: {len(rows)}")

if __name__ == "__main__":
    main()